(defun githublike ()
  (interactive)
  (progn
    ;; (set-frame-font "Bitstream Vera Sans Mono")
    (set-foreground-color "rgb:50/50/50")
    (set-background-color "white")
    (set-face-foreground 'font-lock-comment-face "rgb:90/90/80")
    (set-face-italic-p 'font-lock-comment-face t)
    (set-face-foreground 'font-lock-string-face "rgb:90/00/00")
    (set-face-foreground 'font-lock-keyword-face "black")
    (set-face-bold-p 'font-lock-keyword-face t)
    (set-face-foreground 'font-lock-function-name-face "rgb:90/00/00")
    (set-face-bold-p 'font-lock-function-name-face t)
    (set-face-foreground 'font-lock-variable-name-face "teal")
    (set-face-foreground 'font-lock-type-face "teal")
    (set-face-bold-p 'font-lock-type-face nil)
    (set-face-foreground 'font-lock-builtin-face "black")
    (set-face-bold-p 'font-lock-builtin-face t)
    (set-face-foreground 'font-lock-constant-face "rgb:99/00/73")
    (set-face-bold-p 'font-lock-constant-face nil)
    (set-face-italic-p 'font-lock-constant-face nil)
    (set-face-foreground 'font-lock-warning-face "red")
    (set-face-bold-p 'font-lock-warning-face nil)
  ))

(provide 'githublike)
